/*******************************************************************************
 * Module: spi_master.v                                                        *
 * Description: Parameterized full-duplex SPI master supporting modes 0-3.     *
 * File Created: Tuesday, 28th July 2026 11:44:25 am                           *
 * Author: Long Hai                                                            *
 * -----                                                                       *
 * Last Modified: Tuesday, 28th July 2026 1:48:54 pm                           *
 * Modified By: Long Hai                                                       *
*******************************************************************************/

`timescale 1ns/1ps

module spi_master #(
    parameter integer DATA_WIDTH = 8,   // bits per transfer (each direction)
    parameter integer CLK_DIV    = 3,   // system clocks per SCLK half-period
    parameter integer CPOL       = 0,   // 0 = SCLK idle LOW,  1 = SCLK idle HIGH
    parameter integer CPHA       = 0    // 0 = sample leading edge, 1 = sample trailing
) (
    input  wire                  clk,
    input  wire                  rst_n,          // active-low synchronous reset
    input  wire                  start,          // 1-cycle pulse: begin a transfer
    input  wire [DATA_WIDTH-1:0] tx_data,        // word to send on MOSI
    input  wire                  miso,           // serial input from slave
    output reg                   sclk,           // SPI clock generated by master
    output reg                   mosi,           // serial output to slave
    output reg                   cs_n,           // chip select, active-low
    output reg                   busy,           // HIGH while transfer is active
    output reg                   done,           // 1-cycle pulse when transfer ends
    output reg  [DATA_WIDTH-1:0] rx_data         // word received from slave (valid at done)
);

    // -------------------------------------------------------------------------
    // Localparams
    // -------------------------------------------------------------------------

    // Clamp CLK_DIV to at least 1 to avoid div-by-zero in counter
    localparam integer HALF_PERIOD = (CLK_DIV < 1) ? 1 : CLK_DIV;

    // Minimum bit-width to hold values 0..(HALF_PERIOD-1) and 0..(DATA_WIDTH-1)
    localparam integer DIV_BITS = (HALF_PERIOD < 2) ? 1 : $clog2(HALF_PERIOD);
    localparam integer BIT_BITS = (DATA_WIDTH  < 2) ? 1 : $clog2(DATA_WIDTH);

    // SCLK resting level is determined entirely by CPOL
    localparam SCLK_IDLE = CPOL[0];

    // FSM state encoding
    localparam [1:0] ST_IDLE     = 2'd0;
    localparam [1:0] ST_TRANSFER = 2'd1;
    localparam [1:0] ST_DONE     = 2'd2;

    // -------------------------------------------------------------------------
    // Internal registers
    // -------------------------------------------------------------------------

    reg [1:0]            state;       // current FSM state
    reg [DATA_WIDTH-1:0] tx_latched; // tx_data captured at start; safe to change tx_data after
    reg [DATA_WIDTH-1:0] rx_shift;   // accumulates incoming MISO bits during transfer
    reg [BIT_BITS-1:0]   bit_index;  // which bit (0 = MSB) is being processed now
    reg [DIV_BITS-1:0]   div_count;  // counts system clocks to generate SCLK half-period

    // -------------------------------------------------------------------------
    // Helper functions
    // -------------------------------------------------------------------------

    // Return the bit at position `index` from MSB end (index 0 = MSB)
    function tx_bit;
        input [DATA_WIDTH-1:0] word;
        input integer index;
        begin
            tx_bit = word[DATA_WIDTH-1-index];
        end
    endfunction

    // Write `sample` into position `index` (from MSB) of `word`; return updated word
    function [DATA_WIDTH-1:0] rx_insert;
        input [DATA_WIDTH-1:0] word;
        input integer index;
        input sample;
        reg [DATA_WIDTH-1:0] updated;
        begin
            updated = word;
            updated[DATA_WIDTH-1-index] = sample;
            rx_insert = updated;
        end
    endfunction

    // -------------------------------------------------------------------------
    // FSM — synchronous reset
    // -------------------------------------------------------------------------

    always @(posedge clk) begin
        if (!rst_n) begin
            // De-assert everything; release CS; SCLK returns to idle level
            state      <= ST_IDLE;
            tx_latched <= {DATA_WIDTH{1'b0}};
            rx_shift   <= {DATA_WIDTH{1'b0}};
            rx_data    <= {DATA_WIDTH{1'b0}};
            bit_index  <= 0;
            div_count  <= 0;
            sclk       <= SCLK_IDLE;
            mosi       <= 1'b0;
            cs_n       <= 1'b1;     // CS deasserted (idle)
            busy       <= 1'b0;
            done       <= 1'b0;
        end else begin
            done <= 1'b0;           // done is a 1-cycle pulse; clear every cycle by default

            case (state)

                // ---------------------------------------------------------
                // ST_IDLE: wait for a start request
                // ---------------------------------------------------------
                ST_IDLE: begin
                    sclk      <= SCLK_IDLE;
                    cs_n      <= 1'b1;
                    busy      <= 1'b0;
                    div_count <= 0;
                    bit_index <= 0;

                    if (start) begin
                        tx_latched <= tx_data;              // latch now; tx_data may change after this
                        rx_shift   <= {DATA_WIDTH{1'b0}};  // clear accumulator
                        cs_n       <= 1'b0;                 // assert CS to select slave
                        busy       <= 1'b1;
                        state      <= ST_TRANSFER;

                        // CPHA=0: put MSB on MOSI before first SCLK edge (setup before leading edge)
                        // CPHA=1: MOSI is driven on the leading edge itself, so hold 0 for now
                        mosi <= (CPHA == 0) ? tx_bit(tx_data, 0) : 1'b0;
                    end
                end

                // ---------------------------------------------------------
                // ST_TRANSFER: generate SCLK and shift bits
                //   div_count counts up to HALF_PERIOD-1, then toggles SCLK
                //   Each full SCLK cycle processes one bit
                // ---------------------------------------------------------
                ST_TRANSFER: begin
                    if (div_count < (HALF_PERIOD - 1)) begin
                        div_count <= div_count + 1'b1;  // still counting; hold SCLK

                    end else begin
                        div_count <= 0;                 // reset counter for next half-period

                        // --- First half of SCLK cycle: SCLK was idle, flip to active ---
                        if (sclk == SCLK_IDLE) begin
                            sclk <= ~SCLK_IDLE;         // leading edge

                            if (CPHA == 0)
                                // Mode 0/2: sample MISO on leading edge
                                rx_shift <= rx_insert(rx_shift, bit_index, miso);
                            else
                                // Mode 1/3: drive MOSI on leading edge (shift-out)
                                mosi <= tx_bit(tx_latched, bit_index);

                        // --- Second half of SCLK cycle: SCLK was active, return to idle ---
                        end else begin
                            sclk <= SCLK_IDLE;          // trailing edge

                            if (CPHA != 0)
                                // Mode 1/3: sample MISO on trailing edge
                                rx_shift <= rx_insert(rx_shift, bit_index, miso);

                            // Check if this was the last bit
                            if (bit_index == (DATA_WIDTH - 1)) begin
                                // Commit final received word
                                if (CPHA == 0)
                                    rx_data <= rx_shift;                             // Mode 0/2: already in rx_shift
                                else
                                    rx_data <= rx_insert(rx_shift, bit_index, miso); // Mode 1/3: insert last sample
                                state <= ST_DONE;

                            end else begin
                                bit_index <= bit_index + 1'b1;     // advance to next bit

                                if (CPHA == 0)
                                    // Mode 0/2: pre-drive next MOSI bit before next leading edge
                                    mosi <= tx_bit(tx_latched, bit_index + 1'b1);
                                // Mode 1/3: next MOSI bit will be driven on the next leading edge
                            end
                        end
                    end
                end

                // ---------------------------------------------------------
                // ST_DONE: release CS, assert done for one cycle, return idle
                // ---------------------------------------------------------
                ST_DONE: begin
                    cs_n  <= 1'b1;   // deassert CS — slave transaction closed
                    busy  <= 1'b0;
                    done  <= 1'b1;   // 1-cycle completion pulse
                    mosi  <= 1'b0;   // tri-state / idle MOSI
                    state <= ST_IDLE;
                end

                // Safety net: should never be reached in normal operation
                default: begin
                    state <= ST_IDLE;
                    sclk  <= SCLK_IDLE;
                    cs_n  <= 1'b1;
                    busy  <= 1'b0;
                end

            endcase
        end
    end

endmodule
